main/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView

from . import views

urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^users/$', views.ListUsers.as_view(), name='users'),
    url(r'^products/(?P<user_id>\d+)/$', views.ListProducts.as_view(), name='products'),
    url(r'^codes/$', views.ListCodes.as_view(), name='discount_codes'),
    url(r'^discount_form/$', views.get_discount_form, name='discount_form'),
    url(r'^get_discount_code/$', views.get_discount_code, name='get_discount_code'),

]

test_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
]

main/models.py
from decimal import Decimal

from django.conf import settings
from django.db import models

from .utils import set_default_date

# def set_default_date():
#     return date.today() + timedelta(days=30)


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=4096, blank=True, null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    # image = models.ImageField()

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ('name', 'price')


class DiscountCode(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='discount_codes')
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='discount_codes')
    code = models.CharField(max_length=4, unique=True)
    discount_percents = models.IntegerField()
    created = models.DateField(auto_now_add=True)
    expires = models.DateField(default=set_default_date)

    def __str__(self):
        return self.code

    def calculate_price_after_discount(self):
        price = self.product.price
        result_price = price - Decimal(price * self.discount_percents / 100).\
            quantize(Decimal('.01'))
        return result_price

main/forms.py
from datetime import date

from datetimewidget import widgets
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.forms import ValidationError
from django.utils.translation import ugettext_lazy as _


class LoginForm(AuthenticationForm):
    username = UsernameField(
        max_length=254,
        widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control',
                                      'required': True}),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'required': True}),
    )


class SearchForm(forms.Form):
    query = forms.CharField(max_length=254, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                          'placeholder': 'Find by name'}),
                            required=False)


class DiscountForm(forms.Form):
    discount_percents = forms.IntegerField(max_value=100, min_value=1, widget=forms.NumberInput(attrs={
        'class': 'form-control'
    }))
    expires = forms.DateField(widget=widgets.DateWidget(attrs={'class': 'form-control'},
                                                        usel10n=True, bootstrap_version=3),
                              required=False)
    product_id = forms.CharField(widget=forms.HiddenInput())
    user_id = forms.CharField(widget=forms.HiddenInput())

    def clean_expires(self):
        expires = self.cleaned_data.get('expires')
        if expires:
            if expires <= date.today():
                raise ValidationError(_('Expire date should be greater than current date.'),
                                      code='low_date')
        return expires

main/views.py
from datetime import date
from string import ascii_uppercase, digits

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as AuthLoginView
from django.core.urlresolvers import reverse
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404, render
from django.utils.crypto import get_random_string
from django.views.decorators.http import require_http_methods
from django.views.generic.list import ListView

from . import forms
from .forms import DiscountForm, SearchForm
from .models import DiscountCode, Product
from .utils import (UserPassesTestMixin, ajax_required, check_is_staff,
                    set_default_date, user_passes_test_custom)


class LoginView(AuthLoginView):
    authentication_form = forms.LoginForm
    template_name = 'main/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        url = self.get_redirect_url()
        if not url:
            user = self.request.user
            if user.is_staff:
                url = 'users'
            else:
                url = 'discount_codes'
            url = reverse(url)
        return url


class ListUsers(LoginRequiredMixin, UserPassesTestMixin, ListView):
    http_method_names = ['get']
    paginate_by = getattr(settings, 'PAGINATE_BY', 12)
    template_name = 'main/list_users.html'
    ordering_map = {
        '1': 'date_joined', '2': '-date_joined', '3': 'username'
    }
    context_object_name = 'users_list'
    search_field_name = 'query'

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):
        search_term = self.request.GET.get(self.search_field_name)
        queryset = get_user_model().objects.filter(is_staff=False)
        if search_term:
            queryset = queryset.filter(username__icontains=search_term)
        ordering = self.get_ordering()
        if ordering:
            if self.ordering_num == '3':
                ordering = Lower(ordering)
            queryset = queryset.order_by(ordering)
        return queryset

    def get_ordering(self):
        ordering = self.request.GET.get('ordering')
        if not ordering:
            ordering = '3'
        self.ordering_num = ordering
        ordering = self.ordering_map.get(ordering)
        return ordering

    def get_context_data(self):
        context = super().get_context_data()
        context['search_form'] = SearchForm()
        context['ordering'] = self.ordering_num
        return context


class ListProducts(ListUsers):
    template_name = 'main/list_products.html'
    ordering_map = {
        '1': 'price', '2': '-price', '3': 'name'
    }
    context_object_name = 'products_list'

    def get_queryset(self):
        search_term = self.request.GET.get(self.search_field_name)
        queryset = Product.objects.all()
        if search_term:
            queryset = queryset.filter(name__icontains=search_term)
        ordering = self.get_ordering()
        if ordering:
            if self.ordering_num == '3':
                ordering = Lower(ordering)
            queryset = queryset.order_by(ordering)
        return queryset

    def get_context_data(self):
        context = super().get_context_data()
        context['user_id'] = self.kwargs['user_id']
        return context


@user_passes_test_custom(check_is_staff)
@login_required
@ajax_required
def get_discount_form(request):
    form = DiscountForm(initial={'expires': set_default_date()})
    return render(request, 'main/discount_form.html', {'form': form})


@user_passes_test_custom(check_is_staff)
@login_required
@ajax_required
@require_http_methods(['POST'])
def get_discount_code(request):
    form = DiscountForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        user = get_object_or_404(get_user_model(), id=cd['user_id'])
        product = get_object_or_404(Product, id=cd['product_id'])
        retries = getattr(settings, 'GENERATE_CODE_TRIES', 20)
        DiscountCode.objects.filter(expires__lte=date.today()).delete()
        while True:
            code = get_random_string(4, ascii_uppercase + digits)
            if not DiscountCode.objects.filter(code=code).exists():
                defaults = {'code': code, 'discount_percents': cd['discount_percents']}
                expires = cd['expires']
                if expires:
                    defaults['expires'] = expires
                code_object, _ = DiscountCode.objects.update_or_create(user=user,
                                                                       product=product,
                                                                       defaults=defaults)
                return render(request, 'main/discount_code.html', {'code': code})
            if retries is 0:
                form.add_error(None, 'Cannot generate discount code.'
                                     ' Max number of retries is reached.')
                break
            retries -= 1
    return render(request, 'main/discount_form.html', {'form': form})


class ListCodes(ListUsers):
    template_name = 'main/list_codes.html'
    ordering_map = {
        '1': '-discount_percents', '2': 'expires', '3': 'product__name'
    }
    context_object_name = 'codes_list'

    def test_func(self):
        return not self.request.user.is_staff

    def get_queryset(self):
        search_term = self.request.GET.get(self.search_field_name)
        queryset = DiscountCode.objects.filter(user__id=self.request.user.id).select_related('product')
        if search_term:
            queryset = queryset.filter(product__name__icontains=search_term)
        ordering = self.get_ordering()
        if ordering:
            if self.ordering_num == '3':
                ordering = Lower(ordering)
            queryset = queryset.order_by(ordering)
        return queryset

main/templates/main/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block head %}{% endblock %}
</head>

<body>
   <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <span class="navbar-brand">Test Shop</span>
    </div>
      {% if user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li><p class="navbar-text"><span class="glyphicon glyphicon-user"></span> {{ user.username }}</p></li>
      <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
    </ul>
      {% endif %}
  </div>
</nav>

    <div class="container">
    {% block body %}{% endblock %}
    </div>
</body>
</html>

main/templates/main/discount_code.html
<div class="text-center">
<h3>Discount code was created:</h3>
    <h1 class="text-info">{{ code }}</h1>
<button class="btn btn-default btn-block" data-dismiss="modal">OK</button>
</div>

main/templates/main/discount_form.html
<form id="discount-form" method="post">
    {{ form.media }}
    {% if form.non_field_errors %}
    {% for error in form.non_field_errorss %}
    <p class="bg-danger">{{ error }}</p>
    {% endfor %}
    {% endif %}
    {% for field in form %}
    {% if field.is_hidden %}
    {{ field }}
    {% else %}
    {% if field.errors %}
    {% for error in field.errors %}
    <p class="bg-danger">{{ error }}</p>
    {% endfor %}
    {% endif %}
    <div class="form-group">
          {{ field.label_tag }}
          {{ field }}
    </div>
    {% endif %}
    {% endfor %}
    <input type="submit" id="discount-submit" class="btn btn-primary btn-md" value="Create code"/>
</form>

main/templates/main/list_codes.html
{% extends 'main/base_template.html' %}
{% load staticfiles %}
{% block title %}Test Shop | Discount Codes{% endblock %}

{% block body %}
{% url 'discount_codes' as url %}
<!--<div class="row">-->
    <!--<div id="msg-placeholder" class="col-sm-12">-->

    <!--</div>-->
<!--</div>-->
<div class="row">
    <div class="col-sm-10">
{% include 'main/search_form.html' with form=search_form %}
    </div>
    <div class="col-sm-2">
        {% include 'main/order_dropdown.html' with order1='Product Name' order2='Code expires date' order3='Discount Percents' %}
    </div>
</div>
<!--<div id="products">-->
{% for c in codes_list %}
{% with counter=forloop.counter0 %}
{% if forloop.first %}
<div class="row">
{% elif counter|divisibleby:4 %}
</div>
<div class="row">
    {% endif %}

    <div class="col-sm-3">
        <div class="panel panel-default">
  <div class="panel-body">
      <div class="row">
          <div class="col-sm-12">
      <p class="text-center lead">{{ c.product.name }}</p>
        <p>{{ c.product.description|truncatechars:100 }}</p>
          </div>
      </div>
      <div class="row">
          <div class="col-sm-8">
              <p><strong>Discount Code:</strong></p>
          </div>
          <div class="col-sm-4">
          <p><span class="text-info lead">{{ c.code }}</span></p>
          </div>
      </div>
      <div class="row">
          <div class="col-sm-8">
              <p><strong>Discount Percents:</strong></p>
          </div>
          <div class="col-sm-4">
              <p class="lead">{{ c.discount_percents }}%</p>
          </div>
      </div>
      <div class="row">
          <div class="col-sm-8">
              <p><strong>Old Price:</strong></p>
      </div>
          <div class="col-sm-4">
              <p><s class="text-danger">{{ c.product.price }}$</s></p>
          </div>
      </div>
      <div class="row">
          <div class="col-sm-8">
              <p><strong>New Price:</strong></p>
          </div>
          <div class="col-sm-4">
              <p><span class="text-success">{{ c.calculate_price_after_discount }}$</span></p>
          </div>
      </div>
      <div class="row">
          <div class="col-sm-8">
              <p><strong>Code Expires:</strong></p>
          </div>
          <div class="cols-sm-4">
              <p>{{ c.expires }}</p>
          </div>
      </div>
  </div>
        </div>
    </div>
    {% if forloop.last %}
</div>
{% endif %}
{% endwith %}
{% empty %}
<div class="row">
    <div class="col-sm-12">
        <p class="text-center lead">There's no discount codes yet.</p>
    </div>
</div>
{% endfor %}
<!--</div>-->

{% include 'main/pagination.html' with page=page_obj %}


{% endblock %}

main/templates/main/list_products.html
{% extends 'main/base_template.html' %}
{% load staticfiles %}
{% block title %}Test Shop | Choose Product{% endblock %}
{% block head %}
<script src="{% static 'js/js.cookie.js' %}"></script>
{% endblock%}
{% block body %}
{% url 'products' user_id as url %}
<div class="row">
    <div id="msg-placeholder" class="col-sm-12">

    </div>
</div>
<div class="row">
    <div class="col-sm-10">
{% include 'main/search_form.html' with form=search_form %}
    </div>
    <div class="col-sm-2">
        {% include 'main/order_dropdown.html' with order1='Product Name' order2='Price - From high to low' order3='Price - From low to high' %}
    </div>
</div>
<div id="products">
{% for p in products_list %}
{% with counter=forloop.counter0 %}
{% if forloop.first %}
<div class="row">
{% elif counter|divisibleby:4 %}
</div>
<div class="row">
    {% endif %}

    <div class="col-sm-3">
        <div class="panel panel-default">
  <div class="panel-body">
      <p class="lead text-center">{{ p.name }}</p>
        <p>{{ p.description|truncatechars:100 }}</p>
      <p><strong>Price:</strong> {{ p.price }}$</p>
      <button type="button" class="btn btn-default btn-block" data-id="{{ p.id }}">Add Discount Code</button>
  </div>
        </div>
    </div>
    {% if forloop.last %}
</div>
{% endif %}
{% endwith %}
    {% empty %}
    <div class="row">
    <div class="col-sm-12">
        <p class="text-center lead">There's no products yet.</p>
    </div>
</div>
{% endfor %}
</div>

{% include 'main/pagination.html' with page=page_obj %}

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create discount code</h4>
      </div>
      <div id="modal-body" class="modal-body">
      </div>
      <!--<div class="modal-footer">-->
        <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
      <!--</div>-->
    </div>
  </div>
</div>
<script>
    var csrftoken = Cookies.get('csrftoken');

    function csrfSafeMethod(method) {
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
    });

    function addMsg(msg, msgClass) {
    var msgHolder, msg;
    msg = '<div style="display:none;" class="alert alert-dismissable ' + msgClass +
    '"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>' + msg + '</div>';
    msgHolder = $('#msg-placeholder');
    msgHolder.html(msg);
    msgHolder.find('div.alert').fadeIn(300);
    }



    $(function() {
    $('#myModal').modal({ show: false});
    $('#products').on('click', 'button', function() {
    var body, cursorClass, productId;
    productId = $(this).attr('data-id');
    cursorClass = 'wait-cursor';
    body = $('body');
    body.addClass(cursorClass);
    $.ajax({
    url: {% url 'discount_form' %},
    type: 'GET',
    dataType: 'html'
    }).done(function(html) {
    var modalBody, form;
    modalBody = $('#modal-body');
    modalBody.html(html);
    form = $('#discount-form');
    form.find('#id_product_id').val(productId);
    form.find('#id_user_id').val('{{ user_id }}');
    body.removeClass(cursorClass);
    $('#myModal').modal('show');
    }).fail(function() {
    body.removeClass(cursorClass);
    addMsg('Server error. Please try again.', 'alert-danger');
    });
    });

    $('#myModal').on('click', '#discount-submit', function(e) {
    e.preventDefault();
    var data, body, cursorClass, modalBody;
    cursorClass = 'wait-cursor';
    body = $('body');
    body.addClass(cursorClass);
    modalBody = $('#modal-body');
    data = $('#discount-form').serialize();
    $.ajax({
    url: {% url 'get_discount_code' %},
    type: 'POST',
    data: data,
    dataType: 'html'
    }).done(function(html) {
    body.removeClass(cursorClass);
    modalBody.html(html);
    }).fail(function() {
    $('#myModal').modal('hide');
    body.removeClass(cursorClass);
    addMsg('Server error. Please try again.', 'alert-danger');
    });


    });
    <!--$('#discount-form').submit(function(e) {-->
    <!--e.preventDefault(e);-->
    <!--});-->

    });
</script>

{% endblock %}

main/templates/main/list_users.html
{% extends 'main/base_template.html' %}
{% block title %}Test Shop | Choose User{% endblock %}
{% block body %}
{% url 'users' as url %}
<div class="row">
    <div class="col-sm-10">
{% include 'main/search_form.html' with form=search_form %}
    </div>
    <div class="col-sm-2">
        {% include 'main/order_dropdown.html' with order1='Username' order2='Registration date - New' order3='Registration date - Old' %}
    </div>
</div>
<div class="list-group">
    <div class="list-group-item list-group-item-info row">
        <div class="col-sm-3">Username</div>
        <div class="col-sm-3">Email</div>
        <div class="col-sm-3">First Name</div>
        <div class="col-sm-3">Last Name</div>
    </div>
    {% for u in users_list %}
  <a href="{% url 'products' u.id %}" class="list-group-item row">
      <div class="col-sm-3">{{ u.username }}</div>
      <div class="col-sm-3">{{ u.email }}</div>
      <div class="col-sm-3">{{ u.first_name }}</div>
      <div class="col-sm-3">{{ u.last_name }}</div>
  </a>
    {% empty %}
    <div class="list-group-item-row">
        <p class="lead text-center">There's no users yet.</p>
    </div>
    {% endfor %}
</div>

{% include 'main/pagination.html' with page=page_obj %}




{% endblock %}

main/templates/main/login.html
{% extends 'main/base_template.html' %}
{% block title %}Test Shop | Login{% endblock %}
{% block navbar %}
{% endblock %}
{% block body %}
<div class="row justify-content-center top-margin-big">
    <div class="col-md-8 center-block no-float">
        <form method="post" action="">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
            </div>
            {% endfor %}
            <input type="submit" class="btn btn-primary btn-block" value="Login"/>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/order_dropdown.html
<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Order by
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
        {% with current_page=page_obj.number %}
      <li><a href="{{ url }}?page={{ current_page }}&ordering=3">{{ order1 }}</a></li>
      <li><a href="{{ url }}?page={{ current_page }}&ordering=2">{{ order2 }}</a></li>
      <li><a href="{{ url }}?page={{ current_page }}&ordering=1">{{ order3 }}</a></li>
        {% endwith %}
    </ul>
</div>

main/templates/main/pagination.html
<div class="row">
    <div class="col-sm-12 text-center">
<ul class="pagination">
    {% if page.has_previous %}
    <li><a href="{{ url }}?page={{ paginator.page_range.0 }}&ordering={{ ordering }}">&laquo;</a></li>
    {% with prev_page=page.previous_page_number %}
    <li><a href="{{ url }}?page={{ prev_page }}&ordering={{ ordering }}">{{ prev_page }}</a></li>
    {% endwith %}
    {% endif %}
    <li class="active"><a href="#">{{ page.number }}</a></li>
    {% if page.has_next %}
    {% with next_page=page.next_page_number %}
    <li><a href="{{ url }}?page={{ next_page }}&ordering={{ ordering }}">{{ next_page }}</a></li>
    {% endwith %}
    <!--<li><a href="#">4</a></li>-->
    <!--<li><a href="#">5</a></li>-->
    <li><a href="{{ url }}?page={{ paginator.page_range|last }}&ordering={{ ordering }}">&raquo;</a></li>
    {% endif %}
</ul>
</div>
</div>

main/templates/main/search_form.html
<form class="margin-bot-small" action="" method="get">
    <div class="input-group">
    {{ form.query }}
        <div class="input-group-btn">
        <button class="btn btn-primary" type="submit">
            <i class="glyphicon glyphicon-search"></i>
        </button>
    </div>
    </div>
</form>